Refactor installation script and add support for Django, FastAPI, and GPU
- Enhanced `install-dev-environment` script to prompt for installation of Django, FastAPI, and GPU support.
- Implemented cleanup function to remove virtual environment on exit.
- Removed unnecessary comments and improved code readability.
- Added new CLI components including `Codes` class for displaying various status codes.
- Created default aliases JSON configuration for Git and Python commands.
- Introduced proxy script for executing the main Python script with environment setup.
- Developed `TeaTypeCLI` class for command line interface with metadata.
- Added requirements files for base, FastAPI, and GPU support.
- Implemented LLM inference and model loading functionality in the AI module.
- Added bash helper functions for improved script usability and error handling.

diff --git a/cli/proxy.template b/cli/proxy.template
--- a/cli/proxy.template
+++ b/cli/proxy.template
@@ -1,3 +1,5 @@
+#!/bin/bash
+
 # Copyright (C) 2024-2025 Burak Günaydin
 #
 # Permission is hereby granted, free of charge, to any person obtaining a copy
@@ -10,14 +12,11 @@
 # The above copyright notice and this permission notice shall be included in
 # all copies or substantial portions of the Software.
 
-# From local imports
-from .args.Argument import Argument
-from .args.Command import Command
-from .args.Flag import Flag
-from .BaseCLI import BaseCLI
-from .BaseIsRunningCLI import BaseIsRunningCLI
-from .BaseInstallCLI import BaseInstallCLI
-from .BaseStartCLI import BaseStartCLI
-from .BaseStopCLI import BaseStopCLI
-from .BaseTUI import BaseTUI
-from .MainCLI import MainCLI
+# Exit immediately if a command exits with a non-zero status
+set -e
+
+export PYTHONDONTWRITEBYTECODE=1 # Prevent Python from writing .pyc files
+
+. {{WORKSPACE_PATH}}/teatype-venv/bin/activate
+
+exec {{WORKSPACE_PATH}}/cli/tt "$@" # Execute the main Python script with all passed arguments
diff --git a/scripts/install-dev-environment b/scripts/install-dev-environment
--- a/scripts/install-dev-environment
+++ b/scripts/install-dev-environment
@@ -12,6 +12,11 @@
 # The above copyright notice and this permission notice shall be included in
 # all copies or substantial portions of the Software.
 
+cleanup() {
+    deactivate > /dev/null 2>&1 || true
+    sudo rm -rf "teatype-venv" || true
+}
+
 set -e # Exit immediately if a command exits with a non-zero status
 
 parent_directory=$(dirname "$(dirname "$(readlink -f "$0")")")
@@ -20,19 +25,32 @@ cd "$parent_directory"
 
 . "$parent_directory/util/bash-helper.sh"
 
+implemented_trap cleanup
 
+prompt use_django "Do you want to install django support?" "Y/n" "n"
+prompt use_fastapi "Do you want to install fastapi support?" "Y/n" "n"
+prompt use_gpu "Do you want to install gpu support for ai tools?" "Y/n" "n"
 
-# sudo rm -rf "teatype-venv" || true
+sudo rm -rf "teatype-venv" || true
 
-# python3.11 -m venv teatype-venv
-# . teatype-venv/bin/activate || { echo "Failed to activate virtual environment"; exit 1; }
+python3.11 -m venv teatype-venv
+. teatype-venv/bin/activate || { echo "Failed to activate virtual environment"; exit 1; }
 
-# python3.11 -m pip install --upgrade pip
-# python3.11 -m pip install . -e --
-# python3.11 -m pip install -r "$python_path/requirements/base.txt"
-# python3.11 -m pip install -r "$python_path/requirements/build.txt"
-# python3.11 -m pip install -r "$python_path/requirements/test.txt"
+cd "$python_path"
+python3.11 -m pip install --upgrade pip
+python3.11 -m pip install . -e --
+python3.11 -m pip install -r "$python_path/requirements/base.txt"
+python3.11 -m pip install -r "$python_path/requirements/build.txt"
+python3.11 -m pip install -r "$python_path/requirements/test.txt"
 
-# python3.11 -m pip install -r "$python_path/requirements/django-support.txt"
-# python3.11 -m pip install -r "$python_path/requirements/fastapi-support.txt"
-# python3.11 -m pip install -r "$python_path/requirements/gpu.txt"
+if [[ $use_django == "Y" || $use_django == "y" ]]; then
+    python3.11 -m pip install -r "$python_path/requirements/django-support.txt"
+fi
+
+if [[ $use_fastapi == "Y" || $use_fastapi == "y" ]]; then
+    python3.11 -m pip install -r "$python_path/requirements/fastapi-support.txt"
+fi
+
+if [[ $use_gpu == "Y" || $use_gpu == "y" ]]; then
+    python3.11 -m pip install -r "$python_path/requirements/gpu.txt"
+fi
