feat: Clean up Redis installation script and enhance error handling in llama-cpp-gpu deployment

diff --git a/scripts/deploy/4-install-llama-cpp-gpu b/scripts/deploy/4-install-llama-cpp-gpu
--- a/scripts/deploy/4-install-llama-cpp-gpu
+++ b/scripts/deploy/4-install-llama-cpp-gpu
@@ -19,23 +19,41 @@ grandparent_directory=$(dirname "$parent_directory") # teatype
 
 prepare_sudo_env
 
+set -e # Exit immediately if a command exits with a non-zero status
+
 cleanup() {
-    sudo rm -rf "$grandparent_directory/py/dist/llama-cpp-python"
+    sudo rm -rf "$grandparent_directory/dist/llama-cpp-python"
 }
 implemented_trap cleanup
 
 cd "$grandparent_directory"
 . teatype-venv/bin/activate
 
-mkdir -p "$grandparent_directory/py/dist"
-cd "$grandparent_directory/py/dist"
+mkdir -p "$grandparent_directory/dist"
+cd "$grandparent_directory/dist"
 
 sudo apt-get update -y
-sudo apt-get install -y build-essential cmake python3-dev python3-pip git ninja-build libcurl4-openssl-dev gcc-12 g++-12 libgomp1
+sudo apt-get install -y build-essential cmake python3-dev python3-pip git ninja-build libcurl4-openssl-dev gcc-12 g++-12 libgomp1 software-properties-common
+sudo add-apt-repository ppa:graphics-drivers/ppa
 sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-12 60 --slave /usr/bin/g++ g++ /usr/bin/g++-12
+wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2404/x86_64/cuda-ubuntu2404.pin
+sudo mv cuda-ubuntu2404.pin /etc/apt/preferences.d/cuda-repository-pin-600
+wget https://developer.download.nvidia.com/compute/cuda/13.0.0/local_installers/cuda-repo-ubuntu2404-13-0-local_13.0.0-580.65.06-1_amd64.deb
+sudo dpkg -i cuda-repo-ubuntu2404-13-0-local_13.0.0-580.65.06-1_amd64.deb
+sudo cp /var/cuda-repo-ubuntu2404-13-0-local/cuda-*-keyring.gpg /usr/share/keyrings/
+sudo apt-get -y install cuda-toolkit-13-0 cuda-drivers
+sudo apt-get update -y
+sudo apt-get autoremove -y
+echo 'export PATH=/usr/local/cuda/bin:$PATH' >> ~/.bashrc
+echo 'export LD_LIBRARY_PATH=/usr/local/cuda/lib64:$LD_LIBRARY_PATH' >> ~/.bashrc
+source ~/.bashrc
 
-git clone --recurse-submodules https://github.com/abetlen/llama-cpp-python.git | echo "Cloned llama-cpp-python repository"
-cd llama-cpp-python
+if [ -d "llama-cpp-python" ]; then
+    echo "llama-cpp-python directory already exists, skipping cloning"
+else
+    git clone --recurse-submodules https://github.com/abetlen/llama-cpp-python.git
+fi
+cd "$grandparent_directory/dist/llama-cpp-python"
 
 # Set environment variables for the build
 export PATH=/usr/local/cuda/bin:$PATH
@@ -50,4 +68,4 @@ export CXX="/usr/bin/g++-12"
 export CUDAHOSTCXX="/usr/bin/g++-12"
 
 # Run the installation from the cloned directory
-pip install --no-cache-dir .
+python3.11 -m pip install --no-cache-dir .
